[package]
name = "verifier_cli"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
bbs = "0.4.1"
clap = { version = "4.5.36", features = ["derive"] }
hex = "0.4.3"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
