[package]
name = "ssi_wallet"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
bbs = "0.4.1"
bincode = { version = "2.0.1", features = ["serde"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_bytes = "0.11.17"
serde_derive = "1.0.219"
serde_json = "1.0.140"
